main:
  - name: "Start"
    url: "/de/"
    weight: 1
  - name: "Über uns"
    url: "/de/about"
    weight: 2

buttons:
  - name: "Kontakt"
    url: "/de/contact"
    weight: 1

footer:
  - name: "Start"
    url: "/de/"
    weight: 1
  - name: "Über uns"
    url: "/de/about"
    weight: 2

footer_legal:
  - name: "Impressum"
    url: "/de/impressum"
    weight: 1
  - name: "Datenschutz"
    url: "/de/datenschutz"
    weight: 2
